# Generated by Django 2.2.1 on 2019-05-27 07:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
