# Generated by Django 2.2.1 on 2019-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_read',
            field=models.IntegerField(default=3),
        ),
    ]
