# Generated by Django 2.2.1 on 2019-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190526_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='admin@linuxdude.gr', max_length=254, verbose_name='email'),
        ),
    ]
